export {default as CurrencyAED} from "./Currency/AED.svg";
export {default as CurrencyAMD} from "./Currency/AMD.svg";
export {default as CurrencyAZN} from "./Currency/AZN.svg";
export {default as CurrencyBUSD} from "./Currency/BUSD.svg";
export {default as CurrencyCHF} from "./Currency/CHF.svg";
export {default as CurrencyCNY} from "./Currency/CNY.svg";
export {default as CurrencyDFT} from "./Currency/DFT.svg";
export {default as CurrencyEUR} from "./Currency/EUR.svg";
export {default as CurrencyGBP} from "./Currency/GBP.svg";
export {default as CurrencyGEL} from "./Currency/GEL.svg";
export {default as CurrencyINR} from "./Currency/INR.svg";
export {default as CurrencyKGS} from "./Currency/KGS.svg";
export {default as CurrencyKZT} from "./Currency/KZT.svg";
export {default as CurrencyRUB} from "./Currency/RUB.svg";
export {default as CurrencyTJS} from "./Currency/TJS.svg";
export {default as CurrencyTRY} from "./Currency/TRY.svg";
export {default as CurrencyUAH} from "./Currency/UAH.svg";
export {default as CurrencyUSD} from "./Currency/USD.svg";
export {default as CurrencyUSDT} from "./Currency/USDT.svg";
export {default as CurrencyUZS} from "./Currency/UZS.svg";
export {default as FlagsKZ} from "./Flags/KZ.svg";
export {default as RegularAirplane} from "./Regular/Airplane.svg";
export {default as RegularAlignCenter} from "./Regular/Align center.svg";
export {default as RegularAlignLeft} from "./Regular/Align left.svg";
export {default as RegularAlignRight} from "./Regular/Align right.svg";
export {default as RegularAlign1} from "./Regular/Align1.svg";
export {default as RegularArrowBackwords} from "./Regular/Arrow backwords.svg";
export {default as RegularArrowDownBig} from "./Regular/Arrow down big.svg";
export {default as RegularArrowDown} from "./Regular/Arrow down.svg";
export {default as RegularArrowLeftBig} from "./Regular/Arrow left big.svg";
export {default as RegularArrowLeft} from "./Regular/Arrow left.svg";
export {default as RegularArrowRightBig} from "./Regular/Arrow right big.svg";
export {default as RegularArrowRight} from "./Regular/Arrow right.svg";
export {default as RegularArrowUpBig} from "./Regular/Arrow up big.svg";
export {default as RegularArrowUp} from "./Regular/Arrow up.svg";
export {default as RegularAttach} from "./Regular/Attach.svg";
export {default as RegularBack} from "./Regular/Back.svg";
export {default as RegularBag} from "./Regular/Bag.svg";
export {default as RegularBank} from "./Regular/Bank.svg";
export {default as RegularBattery} from "./Regular/Battery.svg";
export {default as RegularBook} from "./Regular/Book.svg";
export {default as RegularBookmark} from "./Regular/Bookmark.svg";
export {default as RegularBox} from "./Regular/Box.svg";
export {default as RegularBrowser} from "./Regular/Browser.svg";
export {default as RegularBusinessChart} from "./Regular/Business chart.svg";
export {default as RegularCalendar} from "./Regular/Calendar.svg";
export {default as RegularCamera} from "./Regular/Camera.svg";
export {default as RegularCar} from "./Regular/Car.svg";
export {default as RegularCard} from "./Regular/Card.svg";
export {default as RegularChart} from "./Regular/Chart.svg";
export {default as RegularChecklist} from "./Regular/Checklist.svg";
export {default as RegularClock} from "./Regular/Clock.svg";
export {default as RegularCode} from "./Regular/Code.svg";
export {default as RegularCoffee} from "./Regular/Coffee.svg";
export {default as RegularCoin} from "./Regular/Coin.svg";
export {default as RegularColour} from "./Regular/Colour.svg";
export {default as RegularCook} from "./Regular/Cook.svg";
export {default as RegularCopy} from "./Regular/Copy.svg";
export {default as RegularCross} from "./Regular/Cross.svg";
export {default as RegularDelete} from "./Regular/Delete.svg";
export {default as RegularDesign} from "./Regular/Design.svg";
export {default as RegularDownload} from "./Regular/Download.svg";
export {default as RegularEdit} from "./Regular/Edit.svg";
export {default as RegularEducation} from "./Regular/Education.svg";
export {default as RegularExclaimationPointWithoutCircle} from "./Regular/ExclaimationPointWithoutCircle.svg";
export {default as RegularEyeClosed} from "./Regular/Eye closed.svg";
export {default as RegularEyeOpen} from "./Regular/Eye open.svg";
export {default as RegularFaceID} from "./Regular/Face ID.svg";
export {default as RegularFile} from "./Regular/File.svg";
export {default as RegularFilter} from "./Regular/Filter.svg";
export {default as RegularFilter1} from "./Regular/Filter-1.svg";
export {default as RegularFlashOn} from "./Regular/Flash on.svg";
export {default as RegularFlash} from "./Regular/Flash.svg";
export {default as RegularFolder} from "./Regular/Folder.svg";
export {default as RegularGraph} from "./Regular/Graph.svg";
export {default as RegularGraphic} from "./Regular/Graphic.svg";
export {default as RegularHistory} from "./Regular/History.svg";
export {default as RegularHome} from "./Regular/Home.svg";
export {default as RegularHyphen} from "./Regular/Hyphen.svg";
export {default as RegularImage} from "./Regular/Image.svg";
export {default as RegularInfo} from "./Regular/Info.svg";
export {default as RegularJoystick} from "./Regular/Joystick.svg";
export {default as RegularKey} from "./Regular/Key.svg";
export {default as RegularLayers} from "./Regular/Layers.svg";
export {default as RegularLike} from "./Regular/Like.svg";
export {default as RegularLink} from "./Regular/Link.svg";
export {default as RegularLock} from "./Regular/Lock.svg";
export {default as RegularLogin} from "./Regular/Login.svg";
export {default as RegularLogout} from "./Regular/Logout.svg";
export {default as RegularMagic} from "./Regular/Magic.svg";
export {default as RegularMail} from "./Regular/Mail.svg";
export {default as RegularMedical} from "./Regular/Medical.svg";
export {default as RegularMessage} from "./Regular/Message.svg";
export {default as RegularMic} from "./Regular/Mic.svg";
export {default as RegularMinus} from "./Regular/Minus.svg";
export {default as RegularMonitor} from "./Regular/Monitor.svg";
export {default as RegularMoon} from "./Regular/Moon.svg";
export {default as RegularMore} from "./Regular/More.svg";
export {default as RegularMusic} from "./Regular/Music.svg";
export {default as RegularNavigation} from "./Regular/Navigation.svg";
export {default as RegularNotification} from "./Regular/Notification.svg";
export {default as RegularNotificationNo} from "./Regular/NotificationNo.svg";
export {default as RegularPause} from "./Regular/Pause.svg";
export {default as RegularPen} from "./Regular/Pen.svg";
export {default as RegularPhoneCall} from "./Regular/Phone call.svg";
export {default as RegularPin} from "./Regular/Pin.svg";
export {default as RegularPlay} from "./Regular/Play.svg";
export {default as RegularPlus} from "./Regular/Plus.svg";
export {default as RegularPremium} from "./Regular/Premium.svg";
export {default as RegularPrint} from "./Regular/Print.svg";
export {default as RegularPromote} from "./Regular/Promote.svg";
export {default as RegularQR} from "./Regular/QR.svg";
export {default as RegularQuestionMark} from "./Regular/Question mark.svg";
export {default as RegularReceipt} from "./Regular/Receipt.svg";
export {default as RegularRedirect} from "./Regular/Redirect.svg";
export {default as RegularRefresh} from "./Regular/Refresh.svg";
export {default as RegularSave} from "./Regular/Save.svg";
export {default as RegularSearch} from "./Regular/search.svg";
export {default as RegularSecurity} from "./Regular/Security.svg";
export {default as RegularSend} from "./Regular/Send.svg";
export {default as RegularServer} from "./Regular/Server.svg";
export {default as RegularSettings} from "./Regular/Settings.svg";
export {default as RegularShare} from "./Regular/Share.svg";
export {default as RegularShare1} from "./Regular/Share-1.svg";
export {default as RegularShop} from "./Regular/Shop.svg";
export {default as RegularSofa} from "./Regular/Sofa.svg";
export {default as RegularSortDown} from "./Regular/Sort down.svg";
export {default as RegularSortUp} from "./Regular/Sort up.svg";
export {default as RegularSpiner} from "./Regular/Spinner.svg";
export {default as RegularStarActive} from "./Regular/Star Active.svg";
export {default as RegularStar} from "./Regular/Star.svg";
export {default as RegularSuccess} from "./Regular/Success.svg";
export {default as RegularSun} from "./Regular/Sun.svg";
export {default as RegularSupport} from "./Regular/Support.svg";
export {default as RegularTap} from "./Regular/Tap.svg";
export {default as RegularTarget} from "./Regular/Target.svg";
export {default as RegularTennisBall} from "./Regular/Tennis ball.svg";
export {default as RegularThumbDown} from "./Regular/Thumb down.svg";
export {default as RegularThumbUp} from "./Regular/Thumb up.svg";
export {default as RegularTilda} from "./Regular/Tilda.svg";
export {default as RegularUnlock} from "./Regular/Unlock.svg";
export {default as RegularUpload} from "./Regular/Upload.svg";
export {default as RegularUpload1} from "./Regular/Upload-1.svg";
export {default as RegularUserProfile} from "./Regular/User profile.svg";
export {default as RegularUser} from "./Regular/User.svg";
export {default as RegularUsers} from "./Regular/Users.svg";
export {default as RegularVacation} from "./Regular/Vacation.svg";
export {default as RegularVideo} from "./Regular/Video.svg";
export {default as RegularVolumeOff} from "./Regular/Volume off.svg";
export {default as RegularVolumeUp} from "./Regular/Volume up.svg";
export {default as RegularWallet} from "./Regular/Wallet.svg";
export {default as RegularWorld} from "./Regular/World.svg";
export {default as StatusError} from "./Status/Error.svg";
export {default as StatusPending} from "./Status/Pending.svg";
export {default as StatusSuccess} from "./Status/Success.svg";
export {default as StatusWarning} from "./Status/Warning.svg";
